using System;
using System.Collections.Generic;
using System.IO;
using MyUI.Runtime;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;
using UnityEngine;

namespace MyUI.Editor
{
    /// <summary>
    /// MyUI 管理窗口（菜单 MyUI → Settings & Registration）：
    /// ① 加载模式：勾选 Addressables / Resources → 保存即应用（生成一行配置并重编译，秒级生效）；
    /// ② Addressables 面板注册：选一个目录（或单片拖入）→ 自动建组（组名可改）、自动入组、
    ///    地址自动 = 类型名、重复跳过、自动关闭 Resources/场景收编。
    /// 全程图形化操作，无需修改任何源码。
    /// </summary>
    public sealed class MyUIWindow : EditorWindow
    {
        private const string ConfigPath = "Assets/MyUI/MyUiLoaderConfig.cs";

        // ① 模式
        private bool _useAddressables = true;

        // ② 注册
        private string _groupName = "UIPanels";
        private string _folder = "";          // 会话变量：仅本次使用，用户临时选择
        private readonly List<GameObject> _dropList = new List<GameObject>();

        private readonly List<string> _log = new List<string>();
        private Vector2 _logScroll;

        [MenuItem("MyUI/Settings & Registration")]
        public static void Open()
        {
            var w = GetWindow<MyUIWindow>(true, "MyUI 管理", true);
            w.minSize = new Vector2(500, 620);
            w.Show();
        }

        private void OnEnable()
        {
            _useAddressables = QueryCurrentMode() == UIAssetMode.Addressables;
            LogLine("窗口已打开。当前模式：" + (_useAddressables ? "Addressables" : "Resources"));
        }

        private static UIAssetMode QueryCurrentMode()
        {
            try
            {
                if (File.Exists(ConfigPath) && File.ReadAllText(ConfigPath).Contains("\"Resources\""))
                {
                    return UIAssetMode.Resources;
                }
            }
            catch (Exception) { }

            return UIAssetMode.Addressables;
        }

        private void OnGUI()
        {
            DrawModeSection();
            EditorGUILayout.Space(8);
            DrawRegistrationSection();
            EditorGUILayout.Space(8);
            DrawLog();
        }

        // ---------- ① 加载模式 ----------
        private void DrawModeSection()
        {
            EditorGUILayout.LabelField("① 加载模式", EditorStyles.boldLabel);
            EditorGUI.BeginDisabledGroup(Application.isPlaying);
            _useAddressables = EditorGUILayout.Toggle("Addressables（默认）", _useAddressables);
            bool res = EditorGUILayout.Toggle("Resources（兼容）", !_useAddressables);
            if (res != !_useAddressables)
            {
                _useAddressables = !res;
            }

            if (GUILayout.Button("保存并应用模式", GUILayout.Height(28)))
            {
                SaveMode();
            }

            EditorGUI.EndDisabledGroup();
            EditorGUILayout.HelpBox("勾选后点「保存并应用模式」即生效（写入 Assets/MyUI/MyUiLoaderConfig.cs 并自动重编译，秒级）。", MessageType.None);
        }

        private void SaveMode()
        {
            string mode = _useAddressables ? "Addressables" : "Resources";
            try
            {
                if (!AssetDatabase.IsValidFolder("Assets/MyUI"))
                {
                    AssetDatabase.CreateFolder("Assets", "MyUI");
                }

                string content =
                    "// AUTO-GENERATED by MyUI (MyUI → Settings & Registration). Do not edit manually.\n" +
                    "namespace MyUI\n{\n    public static class MyUiLoaderConfig\n    {\n" +
                    "        public static readonly string Mode = \"" + mode + "\";\n    }\n}\n";
                File.WriteAllText(ConfigPath, content, new System.Text.UTF8Encoding(false));
                AssetDatabase.ImportAsset(ConfigPath, ImportAssetOptions.ForceSynchronousImport);
                AssetDatabase.Refresh();
                LogLine("已应用模式：" + mode + "（" + ConfigPath + "，重编译后生效）");
            }
            catch (Exception e)
            {
                LogLine("应用模式失败：" + e.Message);
            }
        }

        // ---------- ② Addressables 面板注册 ----------
        private void DrawRegistrationSection()
        {
            EditorGUILayout.LabelField("② Addressables 面板注册", EditorStyles.boldLabel);
            bool hasAd = AddressableAssetSettingsDefaultObject.Settings != null;
            EditorGUI.BeginDisabledGroup(Application.isPlaying || !hasAd);

            _groupName = EditorGUILayout.TextField("组名", _groupName);

            EditorGUILayout.BeginHorizontal();
            _folder = EditorGUILayout.TextField("目标目录（可留空）", _folder);
            if (GUILayout.Button("选择目录…", GUILayout.Width(100)))
            {
                string abs = EditorUtility.OpenFolderPanel("选择面板文件夹（Assets 下）", "Assets", "");
                if (!string.IsNullOrEmpty(abs))
                {
                    string rel = ToAssetPath(abs);
                    if (rel != null)
                    {
                        _folder = rel;
                        LogLine("目录：" + rel);
                    }
                    else
                    {
                        LogLine("目录必须在项目 Assets 下：" + abs);
                    }
                }
            }
            EditorGUILayout.EndHorizontal();

            if (GUILayout.Button("注册目录中所有面板", GUILayout.Height(26)))
            {
                RegisterFolder();
            }

            EditorGUILayout.LabelField("— 或拖入面板预制体（可一次拖多个） —", EditorStyles.centeredGreyMiniLabel);
            Rect dropRect = GUILayoutUtility.GetRect(0f, 48f, GUILayout.ExpandWidth(true));
            GUIStyle ds = GetDropStyle();
            bool hover = dropRect.Contains(Event.current.mousePosition);
            ds.normal.textColor = hover ? new Color(1f, 0.95f, 0.6f) : new Color(0.72f, 0.8f, 1f);
            GUI.Box(dropRect, new GUIContent("⇩  拖入面板预制体（可一次拖多个）  ⇩",
                "在 Project 中多选预制体后拖动到此处"), ds);
            HandleDrop(dropRect);

            if (_dropList.Count > 0)
            {
                foreach (GameObject p in _dropList)
                {
                    EditorGUILayout.LabelField("· " + p.name);
                }

                EditorGUILayout.BeginHorizontal();
                if (GUILayout.Button("注册拖入的面板（" + _dropList.Count + "）", GUILayout.Height(26)))
                {
                    RegisterDropList();
                }

                if (GUILayout.Button("清空", GUILayout.Width(60)))
                {
                    _dropList.Clear();
                }

                EditorGUILayout.EndHorizontal();
            }

            EditorGUI.EndDisabledGroup();

            if (!hasAd)
            {
                EditorGUILayout.HelpBox("Addressables 未初始化：请先打开 Window → Asset Management → Addressables → Groups 完成初始化，本区即可用。", MessageType.Warning);
            }

            EditorGUILayout.HelpBox("组不存在会自动创建；地址自动设为类型名（= 预制体名）；已注册的自动跳过；注册同时关闭 Resources/场景自动收编。", MessageType.Info);
        }

        private static string ToAssetPath(string absPath)
        {
            string data = Application.dataPath;
            if (absPath.StartsWith(data, StringComparison.OrdinalIgnoreCase))
            {
                return "Assets" + absPath.Substring(data.Length).Replace('\\', '/');
            }

            return null;
        }

        private void RegisterFolder()
        {
            if (string.IsNullOrEmpty(_folder) || !AssetDatabase.IsValidFolder(_folder))
            {
                LogLine("目录无效或未选择（例如：Assets/MyUI/Panels）");
                return;
            }

            AddressableAssetSettings settings = AddressableAssetSettingsDefaultObject.Settings;
            if (settings == null)
            {
                LogLine("Addressables 未初始化，无法注册");
                return;
            }

            TryDisableIncludeFlags(settings); // 先关闭自动收编，避免 Resources 目录面板被伪组占用

            string[] prefabGuids = AssetDatabase.FindAssets("t:Prefab", new[] { _folder });
            int added = 0;
            int repeat = 0;
            int notPanel = 0;
            int failed = 0;
            foreach (string guid in prefabGuids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(path);
                if (prefab == null || prefab.GetComponentInChildren<UIPanel>(true) == null)
                {
                    notPanel++;
                    LogLine("跳过（非面板）：" + path);
                    continue;
                }

                string reason;
                if (RegisterEntry(guid, prefab, out reason))
                {
                    added++;
                }
                else if (reason == "repeat")
                {
                    repeat++;
                    LogLine("已存在，跳过：" + prefab.name);
                }
                else
                {
                    failed++;
                    LogLine("注册失败（" + path + "）：" + reason);
                }
            }

            LogLine(string.Format("目录扫描：共 {0} 个预制体（面板 {1} 个）", prefabGuids.Length, prefabGuids.Length - notPanel));
            LogLine(string.Format("目录注册完成：新增 {0}，重复 {1}，非面板 {2}，失败 {3}", added, repeat, notPanel, failed));

            AddressableAssetGroup group = settings.FindGroup(_groupName);
            if (group != null)
            {
                LogLine("当前组 '" + _groupName + "' 条目数：" + (group.entries != null ? group.entries.Count : 0));
            }
        }

        private void RegisterSingle(GameObject prefab)
        {
            if (prefab == null)
            {
                LogLine("请先拖入/选择面板预制体（从 Project 窗口）");
                return;
            }

            string path = AssetDatabase.GetAssetPath(prefab);
            if (string.IsNullOrEmpty(path) || !path.EndsWith(".prefab"))
            {
                LogLine("仅支持 .prefab 资产：" + path);
                return;
            }

            if (prefab.GetComponentInChildren<UIPanel>(true) == null)
            {
                LogLine("该预制体没有 UIPanel 组件，不是面板：" + path);
                return;
            }

            string guid = AssetDatabase.AssetPathToGUID(path);
            string reason;
            if (RegisterEntry(guid, prefab, out reason))
            {
                LogLine("已注册：" + prefab.name + "（组 " + _groupName + "）");
            }
            else
            {
                LogLine(reason == "repeat" ? "已存在，跳过：" + prefab.name : "注册失败（" + prefab.name + "）：" + reason);
            }
        }

        private GUIStyle _dropStyle;

        /// <summary>拖入区样式：边框 + 居中加粗（悬停高亮由调用处设置文字颜色）。</summary>
        private GUIStyle GetDropStyle()
        {
            if (_dropStyle == null)
            {
                _dropStyle = new GUIStyle(EditorStyles.helpBox);
                _dropStyle.alignment = TextAnchor.MiddleCenter;
                _dropStyle.fontStyle = FontStyle.Bold;
                _dropStyle.fontSize = 12;
                _dropStyle.padding = new RectOffset(8, 8, 6, 6);
                _dropStyle.normal.textColor = new Color(0.72f, 0.8f, 1f);
            }

            return _dropStyle;
        }

        /// <summary>处理拖入事件：一次可拖多个预制体进列表（去重）。</summary>
        private void HandleDrop(Rect dropRect)
        {
            Event evt = Event.current;
            if (!dropRect.Contains(evt.mousePosition))
            {
                return;
            }

            if (evt.type == EventType.DragUpdated)
            {
                DragAndDrop.visualMode = DragAndDropVisualMode.Copy;
                evt.Use();
            }
            else if (evt.type == EventType.DragPerform)
            {
                DragAndDrop.AcceptDrag();
                evt.Use();
                foreach (UnityEngine.Object obj in DragAndDrop.objectReferences)
                {
                    var go = obj as GameObject;
                    if (go == null)
                    {
                        continue;
                    }

                    string path = AssetDatabase.GetAssetPath(go);
                    if (string.IsNullOrEmpty(path) || !path.EndsWith(".prefab"))
                    {
                        LogLine("忽略（非预制体）：" + go.name);
                        continue;
                    }

                    if (!_dropList.Contains(go))
                    {
                        _dropList.Add(go);
                    }
                }

                LogLine("拖入 " + _dropList.Count + " 个待注册面板");
            }
        }

        /// <summary>注册拖入列表中的所有面板（一次多个）。</summary>
        private void RegisterDropList()
        {
            int added = 0;
            int repeat = 0;
            foreach (GameObject prefab in _dropList)
            {
                if (prefab == null)
                {
                    continue;
                }

                string path = AssetDatabase.GetAssetPath(prefab);
                if (prefab.GetComponentInChildren<UIPanel>(true) == null)
                {
                    LogLine("跳过（非面板）：" + prefab.name);
                    continue;
                }

                string reason;
                if (RegisterEntry(AssetDatabase.AssetPathToGUID(path), prefab, out reason))
                {
                    LogLine("已注册：" + prefab.name + "（组 " + _groupName + "）");
                    added++;
                }
                else if (reason == "repeat")
                {
                    LogLine("已存在，跳过：" + prefab.name);
                    repeat++;
                }
                else
                {
                    LogLine("注册失败（" + prefab.name + "）：" + reason);
                }
            }

            LogLine("拖入注册完成：新增 " + added + "，重复 " + repeat);
            _dropList.Clear();
        }

        private bool RegisterEntry(string guid, GameObject prefab, out string reason)
        {
            reason = null;
            try
            {
                AddressableAssetSettings settings = AddressableAssetSettingsDefaultObject.Settings;
                if (settings == null)
                {
                    reason = "Addressables 未初始化";
                    return false;
                }

                string typeName = prefab.name; // 类型名 = 预制体名（三统一约定）
                AddressableAssetGroup group = settings.FindGroup(_groupName);
                if (group == null)
                {
                    try
                    {
                        // 传空 schema 列表（避免 DefaultGroup 为空时内部空引用）
                        group = settings.CreateGroup(_groupName, false, false, false,
                            new List<AddressableAssetGroupSchema>(), null);
                    }
                    catch (Exception)
                    {
                        // 部分版本在组已半创建时抛异常：二次查找兜底
                        group = settings.FindGroup(_groupName);
                    }

                    if (group == null)
                    {
                        LogLine("组创建失败：" + _groupName + "（请确认 Addressables 已初始化：Window → Asset Management → Addressables → Groups）");
                    }
                }

                if (group == null)
                {
                    reason = "组创建失败：" + _groupName;
                    return false;
                }

                foreach (AddressableAssetEntry e in group.entries)
                {
                    if (e != null && e.address == typeName)
                    {
                        reason = "repeat";
                        return false;
                    }
                }

                AddressableAssetEntry entry = settings.CreateOrMoveEntry(guid, group);
                if (entry == null)
                {
                    reason = "CreateOrMoveEntry 返回空（可能该资产正被 Resources 收编等特殊条目占用）";
                    return false;
                }

                entry.address = typeName;
                settings.SetDirty(AddressableAssetSettings.ModificationEvent.EntryMoved, null, true, true);
                AssetDatabase.SaveAssets();
                TryDisableIncludeFlags(settings); // 注册成功顺带关闭收编，避免后续被伪组占用
                return true;
            }
            catch (Exception e)
            {
                reason = e.GetType().Name + ": " + e.Message + "\n" + e.StackTrace;
                return false;
            }
        }

        /// <summary>关闭 Addressables 对 Resources 目录与场景的自动收编（尽力而为）。</summary>
        private void TryDisableIncludeFlags(AddressableAssetSettings settings)
        {
            try
            {
                var so = new SerializedObject(settings);
                bool changed = false;
                SerializedProperty p1 = so.FindProperty("m_IncludeResourcesInAddressables");
                SerializedProperty p2 = so.FindProperty("m_IncludeSceneInAddressables");
                if (p1 != null && p1.boolValue)
                {
                    p1.boolValue = false;
                    changed = true;
                }

                if (p2 != null && p2.boolValue)
                {
                    p2.boolValue = false;
                    changed = true;
                }

                if (changed)
                {
                    so.ApplyModifiedProperties();
                    LogLine("已关闭 Addressables 自动收编（Resources/场景）");
                }
            }
            catch (Exception) { }
        }

        // ---------- 日志 ----------
        private void DrawLog()
        {
            EditorGUILayout.BeginHorizontal();
            EditorGUILayout.LabelField("日志", EditorStyles.boldLabel);
            if (GUILayout.Button("清空", GUILayout.Width(60)))
            {
                _log.Clear();
            }

            EditorGUILayout.EndHorizontal();

            _logScroll = EditorGUILayout.BeginScrollView(_logScroll, GUILayout.Height(180));
            if (_log.Count == 0)
            {
                EditorGUILayout.LabelField("（暂无日志）", EditorStyles.centeredGreyMiniLabel, GUILayout.Height(20));
            }

            float width = position.width - 40f;
            foreach (string line in _log)
            {
                GUIContent content = new GUIContent("· " + line);
                float h = EditorStyles.wordWrappedLabel.CalcHeight(content, width);
                EditorGUILayout.SelectableLabel(content.text, EditorStyles.wordWrappedLabel,
                    GUILayout.Width(width), GUILayout.Height(Mathf.Max(20f, h)));
            }

            EditorGUILayout.EndScrollView();
        }

        private void LogLine(string msg)
        {
            _log.Add(DateTime.Now.ToString("HH:mm:ss") + "  " + msg);
        }
    }
}