using System;
using System.Collections.Generic;
using System.IO;
using MyUI.Runtime;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;
using UnityEngine;

namespace MyUI.Editor
{
    /// <summary>
    /// MyUI 管理窗口（菜单 MyUI → Settings & Registration）：
    /// ① 加载模式：勾选 Addressables / Resources → 保存即应用（生成一行配置并重编译，秒级生效）；
    /// ② Addressables 面板注册：选一个目录（或单片拖入）→ 自动建组（组名可改）、自动入组、
    ///    地址自动 = 类型名、重复跳过、自动关闭 Resources/场景收编。
    /// 全程图形化操作，无需修改任何源码。
    /// </summary>
    public sealed class MyUIWindow : EditorWindow
    {
        private const string ConfigPath = "Assets/MyUI/MyUiLoaderConfig.cs";

        // ① 模式
        private bool _useAddressables = true;

        // ② 注册
        private string _groupName = "UIPanels";
        private string _folder = "";          // 会话变量：仅本次使用，用户临时选择
        private GameObject _singlePrefab;

        private readonly List<string> _log = new List<string>();
        private Vector2 _logScroll;

        [MenuItem("MyUI/Settings & Registration")]
        public static void Open()
        {
            var w = GetWindow<MyUIWindow>(true, "MyUI 管理", true);
            w.minSize = new Vector2(500, 620);
            w.Show();
        }

        private void OnEnable()
        {
            _useAddressables = QueryCurrentMode() == UiAssetMode.Addressables;
            LogLine("窗口已打开。当前模式：" + (_useAddressables ? "Addressables" : "Resources"));
        }

        private static UiAssetMode QueryCurrentMode()
        {
            try
            {
                if (File.Exists(ConfigPath) && File.ReadAllText(ConfigPath).Contains("\"Resources\""))
                {
                    return UiAssetMode.Resources;
                }
            }
            catch (Exception) { }

            return UiAssetMode.Addressables;
        }

        private void OnGUI()
        {
            DrawModeSection();
            EditorGUILayout.Space(8);
            DrawRegistrationSection();
            EditorGUILayout.Space(8);
            DrawLog();
        }

        // ---------- ① 加载模式 ----------
        private void DrawModeSection()
        {
            EditorGUILayout.LabelField("① 加载模式", EditorStyles.boldLabel);
            EditorGUI.BeginDisabledGroup(Application.isPlaying);
            _useAddressables = EditorGUILayout.Toggle("Addressables（默认）", _useAddressables);
            bool res = EditorGUILayout.Toggle("Resources（兼容）", !_useAddressables);
            if (res != !_useAddressables)
            {
                _useAddressables = !res;
            }

            if (GUILayout.Button("保存并应用模式", GUILayout.Height(28)))
            {
                SaveMode();
            }

            EditorGUI.EndDisabledGroup();
            EditorGUILayout.HelpBox("勾选后点「保存并应用模式」即生效（写入 Assets/MyUI/MyUiLoaderConfig.cs 并自动重编译，秒级）。", MessageType.None);
        }

        private void SaveMode()
        {
            string mode = _useAddressables ? "Addressables" : "Resources";
            try
            {
                if (!AssetDatabase.IsValidFolder("Assets/MyUI"))
                {
                    AssetDatabase.CreateFolder("Assets", "MyUI");
                }

                string content =
                    "// AUTO-GENERATED by MyUI (MyUI → Settings & Registration). Do not edit manually.\n" +
                    "namespace MyUI\n{\n    public static class MyUiLoaderConfig\n    {\n" +
                    "        public static readonly string Mode = \"" + mode + "\";\n    }\n}\n";
                File.WriteAllText(ConfigPath, content, new System.Text.UTF8Encoding(false));
                AssetDatabase.ImportAsset(ConfigPath, ImportAssetOptions.ForceSynchronousImport);
                AssetDatabase.Refresh();
                LogLine("已应用模式：" + mode + "（" + ConfigPath + "，重编译后生效）");
            }
            catch (Exception e)
            {
                LogLine("应用模式失败：" + e.Message);
            }
        }

        // ---------- ② Addressables 面板注册 ----------
        private void DrawRegistrationSection()
        {
            EditorGUILayout.LabelField("② Addressables 面板注册", EditorStyles.boldLabel);
            bool hasAd = AddressableAssetSettingsDefaultObject.Settings != null;
            EditorGUI.BeginDisabledGroup(Application.isPlaying || !hasAd);

            _groupName = EditorGUILayout.TextField("组名", _groupName);

            EditorGUILayout.BeginHorizontal();
            _folder = EditorGUILayout.TextField("目标目录（可留空）", _folder);
            if (GUILayout.Button("选择目录…", GUILayout.Width(100)))
            {
                string abs = EditorUtility.OpenFolderPanel("选择面板文件夹（Assets 下）", "Assets", "");
                if (!string.IsNullOrEmpty(abs))
                {
                    string rel = ToAssetPath(abs);
                    if (rel != null)
                    {
                        _folder = rel;
                        LogLine("目录：" + rel);
                    }
                    else
                    {
                        LogLine("目录必须在项目 Assets 下：" + abs);
                    }
                }
            }
            EditorGUILayout.EndHorizontal();

            if (GUILayout.Button("注册目录中所有面板", GUILayout.Height(26)))
            {
                RegisterFolder();
            }

            EditorGUILayout.LabelField("— 或单片注册 —", EditorStyles.centeredGreyMiniLabel);
            EditorGUILayout.BeginHorizontal();
            _singlePrefab = (GameObject)EditorGUILayout.ObjectField("预制体", _singlePrefab, typeof(GameObject), false);
            if (GUILayout.Button("注册该面板", GUILayout.Width(100)))
            {
                RegisterSingle(_singlePrefab);
            }

            EditorGUILayout.EndHorizontal();
            EditorGUI.EndDisabledGroup();

            if (!hasAd)
            {
                EditorGUILayout.HelpBox("Addressables 未初始化：请先打开 Window → Asset Management → Addressables → Groups 完成初始化，本区即可用。", MessageType.Warning);
            }

            EditorGUILayout.HelpBox("组不存在会自动创建；地址自动设为类型名（= 预制体名）；已注册的自动跳过；注册同时关闭 Resources/场景自动收编。", MessageType.Info);
        }

        private static string ToAssetPath(string absPath)
        {
            string data = Application.dataPath;
            if (absPath.StartsWith(data, StringComparison.OrdinalIgnoreCase))
            {
                return "Assets" + absPath.Substring(data.Length).Replace('\\', '/');
            }

            return null;
        }

        private void RegisterFolder()
        {
            if (string.IsNullOrEmpty(_folder) || !AssetDatabase.IsValidFolder(_folder))
            {
                LogLine("目录无效或未选择（例如：Assets/MyUI/Panels）");
                return;
            }

            int ok = 0;
            int skip = 0;
            foreach (string guid in AssetDatabase.FindAssets("t:Prefab", new[] { _folder }))
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(path);
                if (prefab == null || prefab.GetComponentInChildren<UiPanel>(true) == null)
                {
                    skip++;
                    continue;
                }

                if (RegisterEntry(guid, prefab))
                {
                    ok++;
                }
                else
                {
                    skip++;
                }
            }

            LogLine("目录注册完成：新增 " + ok + " 个，跳过 " + skip + " 个（非面板或重复）");
        }

        private void RegisterSingle(GameObject prefab)
        {
            if (prefab == null)
            {
                LogLine("请先拖入/选择面板预制体（从 Project 窗口）");
                return;
            }

            string path = AssetDatabase.GetAssetPath(prefab);
            if (string.IsNullOrEmpty(path) || !path.EndsWith(".prefab"))
            {
                LogLine("仅支持 .prefab 资产：" + path);
                return;
            }

            if (prefab.GetComponentInChildren<UiPanel>(true) == null)
            {
                LogLine("该预制体没有 UiPanel 组件，不是面板：" + path);
                return;
            }

            string guid = AssetDatabase.AssetPathToGUID(path);
            RegisterEntry(guid, prefab);
        }

        private bool RegisterEntry(string guid, GameObject prefab)
        {
            try
            {
                AddressableAssetSettings settings = AddressableAssetSettingsDefaultObject.Settings;
                if (settings == null)
                {
                    LogLine("Addressables 未初始化，无法注册");
                    return false;
                }

                string typeName = prefab.name; // 类型名 = 预制体名（三统一约定）
                AddressableAssetGroup group = settings.FindGroup(_groupName);
                if (group == null)
                {
                    group = settings.CreateGroup(_groupName, false, false, false, settings.DefaultGroup.Schemas, null);
                    LogLine("已自动创建组：" + _groupName);
                }

                foreach (AddressableAssetEntry e in group.entries)
                {
                    if (e != null && e.address == typeName)
                    {
                        LogLine("已存在，跳过：" + typeName);
                        return false;
                    }
                }

                AddressableAssetEntry entry = settings.CreateOrMoveEntry(guid, group);
                if (entry == null)
                {
                    LogLine("CreateOrMoveEntry 失败：" + typeName);
                    return false;
                }

                entry.address = typeName;
                settings.SetDirty(AddressableAssetSettings.ModificationEvent.EntryMoved, null, true, true);
                AssetDatabase.SaveAssets();
                TryDisableIncludeFlags(settings);
                LogLine("已注册：" + typeName + "（组 " + _groupName + "）");
                return true;
            }
            catch (Exception e)
            {
                LogLine("注册失败：" + e.Message);
                return false;
            }
        }

        /// <summary>关闭 Addressables 对 Resources 目录与场景的自动收编（尽力而为）。</summary>
        private static void TryDisableIncludeFlags(AddressableAssetSettings settings)
        {
            try
            {
                var so = new SerializedObject(settings);
                bool changed = false;
                SerializedProperty p1 = so.FindProperty("m_IncludeResourcesInAddressables");
                SerializedProperty p2 = so.FindProperty("m_IncludeSceneInAddressables");
                if (p1 != null && p1.boolValue)
                {
                    p1.boolValue = false;
                    changed = true;
                }

                if (p2 != null && p2.boolValue)
                {
                    p2.boolValue = false;
                    changed = true;
                }

                if (changed)
                {
                    so.ApplyModifiedProperties();
                    LogLine("已关闭 Addressables 自动收编（Resources/场景）");
                }
            }
            catch (Exception) { }
        }

        // ---------- 日志 ----------
        private void DrawLog()
        {
            EditorGUILayout.LabelField("日志", EditorStyles.boldLabel);
            _logScroll = EditorGUILayout.BeginScrollView(_logScroll, GUILayout.Height(150));
            foreach (string line in _log)
            {
                EditorGUILayout.LabelField("· " + line);
            }

            EditorGUILayout.EndScrollView();
        }

        private void LogLine(string msg)
        {
            _log.Add(DateTime.Now.ToString("HH:mm:ss") + "  " + msg);
        }
    }
}